# permissions for end users to view attractors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: attractor-viewer-role
rules:
- apiGroups:
  - meridio.nordix.org
  resources:
  - attractors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - attractors/status
  verbs:
  - get
