# permissions for end users to edit attractors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: attractor-editor-role
rules:
- apiGroups:
  - meridio.nordix.org
  resources:
  - attractors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - attractors/status
  verbs:
  - get
