# permissions for end users to view conduits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conduit-viewer-role
rules:
- apiGroups:
  - meridio.nordix.org
  resources:
  - conduits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - conduits/status
  verbs:
  - get
