# permissions for end users to edit conduits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conduit-editor-role
rules:
- apiGroups:
  - meridio.nordix.org
  resources:
  - conduits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - conduits/status
  verbs:
  - get
