# permissions for end users to view flows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flow-viewer-role
rules:
- apiGroups:
  - meridio.nordix.org
  resources:
  - flows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - flows/status
  verbs:
  - get
