apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nsp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nsp-role
subjects:
- kind: ServiceAccount
  name: nsp
  namespace: system 
