
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: nsp-role
  namespace: system
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - watch
