# permissions for end users to view streams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stream-viewer-role
rules:
- apiGroups:
  - meridio.nordix.org
  resources:
  - streams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - streams/status
  verbs:
  - get
