# permissions for end users to edit streams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stream-editor-role
rules:
- apiGroups:
  - meridio.nordix.org
  resources:
  - streams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - streams/status
  verbs:
  - get
