# permissions for end users to view trenches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trench-viewer-role
rules:
- apiGroups:
  - meridio.nordix.org
  resources:
  - trenches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - trenches/status
  verbs:
  - get
