# permissions for end users to edit trenches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trench-editor-role
rules:
- apiGroups:
  - meridio.nordix.org
  resources:
  - trenches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - trenches/status
  verbs:
  - get
