# permissions for end users to edit vips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vip-editor-role
rules:
- apiGroups:
  - meridio.nordix.org
  resources:
  - vips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - vips/status
  verbs:
  - get
