---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "meridio.configuration" . }}
data:
  meridio.conf: |
    vips: [{{ template "meridio.vips" . }}]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "meridio.serviceAccount" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: meridio-configuration-role-{{ .Values.trench.name }}
rules:
- apiGroups: 
  - ""
  resources: 
  - configmaps
  verbs: 
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: meridio-configuration-role-binding-{{ .Values.trench.name }}
subjects:
- kind: ServiceAccount
  name: {{ template "meridio.serviceAccount" . }}
roleRef:
  kind: Role
  name: meridio-configuration-role-{{ .Values.trench.name }}
  apiGroup: rbac.authorization.k8s.io